### ISSUE TITLE
pgModeler

### ISSUE THREAD

**Issue by dncgst** [archeos/ArcheOS#105]
I was searching for a ER DB diagram tool and I found this PostgreSQL Database Modeler[0], distributed on GitHub[1] under GPL3.
It seems quite powerful and useful in combination with pgAdmin. I specially like the reverse engineering feature and the support for PostGIS. Working with PostgreSQL, I prefer it to general UML diagram tools like Dia.

[0] http://www.pgmodeler.com.br/
[1] https://github.com/pgmodeler/pgmodeler

**Comment by lucaarcteam** [comment]
Thanks Domenico. I close this issue since we will try to package PgModeler in order to replace PgDesigner (we have already an issue for this).
