### ISSUE TITLE
Cura for 3D printing

### ISSUE THREAD

**Issue by lucaarcteam** [archeos/ArcheOS#116]
After some test I think Cura could be the right software to support 3D printing in Cultural Heritage ad archeology. It seems that packaging of Cura is performed aso by a team of Debian: https://wiki.debian.org/3D-printer

We should add the package in ArcheOS Theodoric.

**Comment by alearcteam** [comment]
Hi,
i suggest also this github repo:
http://raspibo.ofpcina.net/discussion/view/3364/software-cura-per-3d-printer

**Comment by lucaarcteam** [comment]
Today Cura has been added to the repo. I close the issue and open a new issue for ArcheOS next in ordr to source package it.
