### ISSUE TITLE
Dendrochronology packages software selection

### ISSUE THREAD

**Issue by lucaarcteam** [archeos/ArcheOS#132]
We should choose the dendrochronological software fo ArcheOS-next. The candidates should be:
1. Corina
2. Tellervo (desktop and software)
3. Tricycle

As far as I understand from this link (http://dendro.cornell.edu/corina/index.php) Tellervo should replace Corina (which was in ArcheOS Caesar), but I am not sure. Another problem is to understand if ArcheOS should keep btoh of the Tellervo options (desktop and server) or just the desktop application.

**Comment by lucaarcteam** [comment]
To try to understand a little bit more on this problem, I just sent an email do Tellervo development team

**Comment by lucaarcteam** [comment]
Dr Peter Brewer, from Arizona University, already answered my question:

1. Tellervo should replace Corina (Corina is no longer developed)
2. Tellervo server could be treacky to package due to a Postgres dependency and probably for most of the end users Tellervo desktop is enought.

I will update the package list of dendro software of ArcheOS-next thanks to these observations

**Comment by fabfurnari** [comment]
I've just checked and tellervo needs to be repackaged with correct dependency (`libjogl2-java` instead of `libjogl-java`)

**Comment by lucaarcteam** [comment]
Thanks Fab. For the rest is the package valid for us?

**Comment by fabfurnari** [comment]
Yes

**Comment by lucaarcteam** [comment]
I think we can close now this issue. Thanks Dr. Brewer report, we should be able to set up a dendro software group with Tellervo Desktop and Tricycle (witout Corina). I will open two issue for it.
