### ISSUE TITLE
Codename for ArcheOS-next

### ISSUE THREAD

**Issue by lucaarcteam** [archeos/ArcheOS#134]
We need a codename for ArcheOS-next. We can ask the community for ideas, wait one week and than create a poll to choose the right one. Last time we agreed to use a female name for this release.

**Comment by fabfurnari** [comment]
Agreed

**Comment by lucaarcteam** [comment]
I wrote a first post on ATOR about the codename (http://arc-team-open-research.blogspot.it/2015/11/archeos-next-new-release-codename.html) and shared it rhoug FB (https://www.facebook.com/ArcheOS-258977573543/?fref=nf), Linkedin (https://www.linkedin.com/grp/post/3776770-6074650861211049985?trk=groups-post-b-title) and in the archeos-dev ML (http://lists.linux.it/pipermail/archeos-dev/2015-November/000470.html). Waiting for feedbacks

**Comment by lucaarcteam** [comment]
We just noticed that we need the new name ASAP. We closed the survey on the possible names and opened a poll here: http://arc-team-open-research.blogspot.it/2015/11/archeos-next-codename-poll.html. The poll will remain open today and tomorrow

**Comment by lucaarcteam** [comment]
The poll is closed. The winner is Hypatia!
