### ISSUE TITLE
Update Tellervo package

### ISSUE THREAD

**Issue by lucaarcteam** [archeos/ArcheOS#135]
We should update ArcheOS Theodoric package for ArcheOS-next. Here is the report from fabrizio's test on the old package on Jessie:

Tellervo depends on libjogl-java but in Jessie libjogl2-java is present. Consider the option to update the upstream code and dependency.

**Comment by fabfurnari** [comment]
Tellervo v. 1.2.0 has been included into archeos-next distribution with some minor fixes about dependencies.

**Comment by fabfurnari** [comment]
This issue was moved to archeos/archeos-meta#32
