### ISSUE TITLE
Archeos Build fails

### ISSUE THREAD

**Issue by pjduplooy** [archeos/ArcheOS#150]
Hi guys 

I am getting the following build failure (on Ubuntu Box):

It is in the lb_chroot_install-packages install phase:

Need to get 2680 MB of archives.
After this operation, 6381 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  qgis-providers-common libqgis-core2.10.0 libqgis-gui2.10.0 qgis-providers
  libqgis-analysis2.10.0 libqgis-networkanalysis2.10.0 qgis-common qgis
  libqgis-customwidgets python-qgis-common libqgispython2.10.0
  libqgis-server2.10.0 python-qgis qgis-plugin-grass-common libqgisgrass2.10.0
  qgis-plugin-grass qgis-plugin-globe-common qgis-plugin-globe
E: There are problems and -y was used without --force-yes
P: Begin unmounting filesystems...
P: Saving caches...
Reading package lists...
Building dependency tree...
Reading state information...

Can anyone give me some guidance?

Thank you

Pieter

**Comment by fabfurnari** [comment]
Seems that the qgis repos key has changed, this happens sometimes. You are trying to build from the master branch or the new (hypatia) one?

**Comment by pjduplooy** [comment]
Master Branch

**Comment by fabfurnari** [comment]
I've fixed the qgis repository key error, now the build goes fine for master branch.
However I suggest you to checkout to the `hypatia` branch (`git checkout hypatia`) and build with the new version if you want to try.
Keep in mind that Hypatia is still incomplete, some software miss or some menu is incomplete so you should not use it for actual work. Just for testing...

**Comment by pjduplooy** [comment]
Hi

Thx for providing a fix so quickly!!
