### ISSUE TITLE
Evaluate MicMac

### ISSUE THREAD

**Issue by lucaarcteam** [archeos/ArcheOS#46]
We should evaluate also MicMac in the field of SfM - IBM.

More info: http://www.micmac.ign.fr/

Here an example done by Alessandro: http://arc-team-open-research.blogspot.it/2012/03/example-test-of-micmac.html

**Comment by yjmenezes** [comment]
@lucaarcteam 

thx all ArcheOS team, for his work.

I think Micmac would be very useful. Here it is a paper ( 2015 ). MicMac vs Privative SW.
http://viiicncg.ordemengenheiros.pt/fotos/editor2/VIIICNCG/cncg2015_comunicao_24.pdf
and this:
https://github.com/ImproPhoto/pymicmac

btw, take a look:
http://www.openscad.org/
