### ISSUE TITLE
Corina

### ISSUE THREAD

**Issue by lucaarcteam** [archeos/ArcheOS#86]
For archeos-dendrochronology, we need Corina (http://dendro.cornell.edu/corina/), as suggested by Dott. Peter Brown (Cornell University).

**Comment by fabfurnari** [comment]
Ad I read on the officiale website Corina is now deprecated an Tellervo should replace it. 
Do se want to include it anyway into Archeos Theodoric?

**Comment by lucaarcteam** [comment]
You are right Fabrizio,
it seems that Tellervo is the evolution of Corina. The main difference is that Corina should be standalone, while Tellervo is connected also to a server, to performe online comparison of dendrochronological chains. I think we can drop Corina and just add Tellervo

**Comment by lucaarcteam** [comment]
Corina has bee replaced with Tellervo
