### ISSUE TITLE
OpenJUMP

### ISSUE THREAD

**Issue by lucaarcteam** [archeos/ArcheOS#91]
For ArcheOS GIS section, we have to package OpenJUMP (http://www.openjump.org/)

**Comment by lucaarcteam** [comment]
I prepared a binary package for OpenJUMP. The package has to be tested. Alessandro tried to install it on his laptod and it worked, but more tester are needed. The package can be downloaded and tested from this post in ATOR: http://arc-team-open-research.blogspot.it/2015/01/archeos-theodoric-openjump-binary.html

**Comment by fabfurnari** [comment]
Sorry to reopen this but I've started working on the archeos-menu package.
To ensure compatibility I need openjump put icons into /usr/share/icons/hicolor/{48x48,64x64}.
Regarding the desktop file, it could be the same (I use a customized one for the archeos specific menu).
Ask me anything about

**Comment by lucaarcteam** [comment]
OK, so shall I redo the package with icons into /usr/share/icons/hicolor/{48x48,64x64}? Is it only this?
just a question shall I do two different folders (e.g. /usr/share/icons/hicolor/48x48/ and /usr/share/icons/hicolor/64x64/)? and the name and the extension of the icon are ok?
